image: paragoumba/cpp-ci-cd-opengl

stages:
  - tests
  - deploy

pages:
  stage: deploy
  script:
    - doxygen
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

build:
  stage: deploy
  script:
    - cmake -S . -B cmake-build-debug
    - cd cmake-build-debug
    - cmake --build . --target MandelBulb
  artifacts:
    paths:
      - src/cmake-build-debug/MandelBulb
  only:
    - tags

tests:
  stage: tests
  script:
#    - cmake -S . -B cmake-build-debug
#    - cd cmake-build-debug
#    - cmake --build . --target Tests
#    - ../tests/cmake-build-debug/Tests
    - cd tests
    - g++ main.cpp ../lib/glad.c ../src/engine/Camera.cpp ../src/engine/Transformation.cpp ../src/engine/Object.cpp ../src/engine/Window.cpp ../src/engine/exceptions/Exception.cpp -o Tests -lgtest -lgtest_main -lglfw -ldl -lGL
    - ./Tests
