image: cpp-ci-cd-opengl:latest

cache:
  paths:
    - /var/cache/apk

pages:
  stage: deploy
  script:
    - echo $PWD
    - doxygen
  artifacts:
    paths:
      - doc
  only:
    - master

exe:
  stage: deploy
  script:
    - cmake -S . -B cmake-build-debug
    - cd cmake-build-debug
    - cmake --build . --target MandelBulb
  artifacts:
    paths:
      - src/cmake-build-debug/MandelBulb
  only:
    - tags