image: paragoumba/cpp-ci-cd-opengl:1.2

stages:
  - tests
  - deploy

pages:
  stage: deploy
  script:
    - doxygen
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

build:
  stage: deploy
  script:
    - cmake -S . -B cmake-build-debug
    - cd cmake-build-debug
    - cmake --build . --target MandelBulb
  artifacts:
    paths:
      - src/cmake-build-debug/MandelBulb
  only:
    - tags

tests:
  stage: tests
  script:
    - cmake --version
    - cmake -S . -B cmake-build-debug
    - cd cmake-build-debug
    - cmake --build . --target Tests
    - ../tests/cmake-build-debug/Tests