image: paragoumba/cpp-ci-cd-opengl

stages:
  - tests
  - deploy

pages:
  stage: deploy
  script:
    - doxygen
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

build:
  variables:
    OUTPUT_FILE: mandelbulb-$CI_COMMIT_REF_NAME.tar.zst
  stage: deploy
  script:
    - cmake -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Release
    - cmake --build cmake-build-debug --target MandelBulb
    - mkdir src/cmake-build-debug/bin
    - mv src/cmake-build-debug/MandelBulb src/cmake-build-debug/bin/
    - tar caf $OUTPUT_FILE -C src/cmake-build-debug/ bin ../res/
  artifacts:
    paths:
      - $OUTPUT_FILE
  only:
    - tags

tests:
  stage: tests
  script:
    - cmake -S . -B cmake-build-debug
    - cmake --build cmake-build-debug --target MandelBulb
    - cmake --build cmake-build-debug --target Tests
    - ./tests/cmake-build-debug/Tests
