image: paragoumba/cpp-ci-cd-opengl:latest

stages:
  - tests
  - deploy

cache:
  paths:
    - /var/cache/apk

pages:
  stage: deploy
  script:
    - echo $PWD
    - doxygen
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

exe:
  stage: deploy
  script:
    - cmake -S . -B cmake-build-debug
    - cd cmake-build-debug
    - cmake --build . --target MandelBulb
  artifacts:
    paths:
      - src/cmake-build-debug/MandelBulb
  only:
    - tags

tests:
  stage: tests
  script:
    - cmake -S . -B cmake-build-debug
    - cd cmake-build-debug
    - cmake --build . --target Tests
    - ../tests/cmake-build-debug/Tests